"""Workflow execution lock management for VobChat SSE.

The SSE workflow adapter executes LangGraph workflows asynchronously per
``thread_id``. To prevent overlapping runs and race conditions, this module
provides a simple in-process lock manager that enforces at most one active
execution per thread.

Notes
- Locks are per-process and implemented with ``threading.Lock``; use a
  distributed lock if multiple processes can run the same thread.
- A configurable timeout auto-cleans stale executions (e.g., if a worker dies).
- The context manager API yields a ``WorkflowExecution`` record for observability.
"""

import threading
import time
import logging
from typing import Dict, Optional
from contextlib import contextmanager
from dataclasses import dataclass

logger = logging.getLogger(__name__)

@dataclass
class WorkflowExecution:
    """Track a single active workflow execution.

    Attributes:
        thread_id: Logical workflow/thread key.
        start_time: Epoch seconds when the lock was acquired.
        execution_id: Correlation identifier for logs/diagnostics.
        lock: The underlying lock object held during execution.
    """
    thread_id: str
    start_time: float
    execution_id: str
    lock: threading.Lock
    
class WorkflowLockManager:
    """Manage exclusive workflow execution per ``thread_id`` within a process.

    Typical usage:
        with workflow_lock_manager.acquire_workflow_lock(tid) as exec:
            run_workflow()

    Use ``force_acquire=True`` to break a stuck run (e.g., after a crash).
    """
    
    def __init__(self):
        self._thread_locks: Dict[str, WorkflowExecution] = {}
        self._manager_lock = threading.Lock()
        self._execution_timeout = 300  # 5 minutes default timeout
        
    def is_workflow_running(self, thread_id: str) -> bool:
        """Return True if a workflow is currently running for this thread.

        Also performs opportunistic cleanup of timed-out or released locks.
        """
        with self._manager_lock:
            if thread_id not in self._thread_locks:
                return False
                
            execution = self._thread_locks[thread_id]
            
            # Check if execution has timed out
            if time.time() - execution.start_time > self._execution_timeout:
                logger.warning(f"Workflow execution for thread {thread_id} timed out, releasing lock")
                self._cleanup_execution(thread_id)
                return False
                
            # Check if lock is still held
            if not execution.lock.locked():
                logger.info(f"Workflow execution for thread {thread_id} completed, cleaning up")
                self._cleanup_execution(thread_id)
                return False
                
            return True
    
    @contextmanager
    def acquire_workflow_lock(self, thread_id: str, execution_id: Optional[str] = None, force_acquire: bool = False):
        """Acquire an exclusive workflow execution lock for a thread.

        Args:
            thread_id: The workflow thread identifier.
            execution_id: Optional correlation ID; autogenerated if omitted.
            force_acquire: If True, preemptively release any existing lock.

        Yields:
            WorkflowExecution: Metadata about the active execution.

        Raises:
            RuntimeError: If already running and ``force_acquire`` is False, or
                if the lock cannot be acquired within a short timeout.
        """
        if execution_id is None:
            execution_id = f"{thread_id}_{int(time.time() * 1000)}"
            
        logger.info(f"Attempting to acquire workflow lock for thread {thread_id} (execution: {execution_id})")
        
        # Check if workflow is already running (unless force_acquire is True)
        if not force_acquire and self.is_workflow_running(thread_id):
            existing_execution = self._thread_locks[thread_id]
            logger.warning(f"Workflow already running for thread {thread_id} (execution: {existing_execution.execution_id})")
            raise RuntimeError(f"Workflow already running for thread {thread_id}")
        
        # If force_acquire is True, clear any existing state first
        if force_acquire:
            self.force_release_lock(thread_id)
        
        # Create new execution lock
        execution_lock = threading.Lock()
        
        # Try to acquire the lock with timeout
        lock_acquired = execution_lock.acquire(timeout=5)
        if not lock_acquired:
            logger.error(f"Failed to acquire workflow lock for thread {thread_id}")
            raise RuntimeError(f"Failed to acquire workflow lock for thread {thread_id}")
        
        try:
            # Register the execution
            with self._manager_lock:
                execution = WorkflowExecution(
                    thread_id=thread_id,
                    start_time=time.time(),
                    execution_id=execution_id,
                    lock=execution_lock
                )
                self._thread_locks[thread_id] = execution
                
            logger.info(f"Acquired workflow lock for thread {thread_id} (execution: {execution_id})")
            yield execution
            
        finally:
            # Always release and cleanup
            try:
                execution_lock.release()
                logger.info(f"Released workflow lock for thread {thread_id} (execution: {execution_id})")
            except Exception as e:
                logger.error(f"Error releasing workflow lock for thread {thread_id}: {e}")
            
            self._cleanup_execution(thread_id)
    
    def _cleanup_execution(self, thread_id: str):
        """Remove execution tracking for a thread if present."""
        with self._manager_lock:
            if thread_id in self._thread_locks:
                execution = self._thread_locks[thread_id]
                logger.debug(f"Cleaning up workflow execution for thread {thread_id} (execution: {execution.execution_id})")
                del self._thread_locks[thread_id]
    
    def force_release_lock(self, thread_id: str) -> bool:
        """Force-release a workflow lock and clear tracked state.

        Returns:
            bool: True if a lock/state existed and was cleared; False otherwise.
        """
        logger.warning(f"Force releasing workflow lock for thread {thread_id}")
        
        with self._manager_lock:
            if thread_id in self._thread_locks:
                execution = self._thread_locks[thread_id]
                try:
                    if execution.lock.locked():
                        execution.lock.release()
                        logger.info(f"Successfully released lock for thread {thread_id}")
                except Exception as e:
                    logger.error(f"Error force releasing lock for thread {thread_id}: {e}")
                    
                self._cleanup_execution(thread_id)
                logger.info(f"Cleaned up workflow execution state for thread {thread_id}")
                return True
        
        logger.debug(f"No active workflow found for thread {thread_id} to force release")
        return False
    
    def clear_thread_state(self, thread_id: str) -> bool:
        """Clear all known workflow state for a thread.

        Currently equivalent to ``force_release_lock``; hook for future cleanup
        of external state (e.g., checkpoints) if required.
        """
        logger.info(f"Clearing all workflow state for thread {thread_id}")
        
        # Force release any locks
        lock_released = self.force_release_lock(thread_id)
        
        # Clear any additional state that might exist
        # This could include clearing checkpointed state if needed
        
        return lock_released
    
    def get_active_executions(self) -> Dict[str, str]:
        """Return a mapping of thread_id to execution_id for active locks.

        Stale or released executions are cleaned up as part of this call.
        """
        active = {}
        current_time = time.time()
        
        with self._manager_lock:
            for thread_id, execution in list(self._thread_locks.items()):
                # Clean up timed out executions
                if current_time - execution.start_time > self._execution_timeout:
                    logger.warning(f"Cleaning up timed out execution for thread {thread_id}")
                    self._cleanup_execution(thread_id)
                    continue
                    
                if execution.lock.locked():
                    active[thread_id] = execution.execution_id
                else:
                    # Lock was released, clean up
                    self._cleanup_execution(thread_id)
        
        return active
    
    def set_timeout(self, timeout_seconds: int):
        """Set the auto-timeout for active executions in seconds."""
        self._execution_timeout = timeout_seconds
        logger.info(f"Workflow execution timeout set to {timeout_seconds} seconds")

# Global singleton instance
workflow_lock_manager = WorkflowLockManager()
