from setuptools import setup, find_packages

setup(
    name="vobchat",  # Change this to a unique name
    version="0.1.0",
    author="Xan Morice-Atkinson",
    author_email="xan.morice-atkinson@port.ac.uk",
    description="A Dash web application for talking to VoB Data.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    packages=find_packages(where="src/vobchat/"),
    package_dir={"": "src/vobchat/"},
    install_requires=[
        "argon2_cffi",
        "authlib",
        "celery",
        "configparser",
        "dash-bootstrap-components",
        "dash-extensions",
        "dash-leaflet",
        "dash",
        "dash[diskcache]",
        "debugpy",
        "diskcache",
        "flask_login",
        "flask_sqlalchemy",
        "flask-socketio",
        "flask",
        "flask",
        "GeoAlchemy2",
        "geopandas",
        "gevent",
        "grandalf",
        "gunicorn",
        "langchain_community",
        "langchain_ollama",
        "langchain_openai",
        "langchain",
        "langgraph",
        "matplotlib",
        "networkx",
        "numpy",
        "pandas",
        "passlib",
        "plotly",
        "psycopg2-binary",
        "pyproj",
        "redis",
        "shapely",
        "sqlalchemy",
        "sshtunnel",
        "trio",
    ],
    include_package_data=True,
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    entry_points={
        "console_scripts": [
            "vob=app.main:run",  # Adjust to your main script
        ],
    },
)
