# app/components/chat.py
from dash import dcc, html
import dash_bootstrap_components as dbc


def create_chat_layout():
    return html.Div([
        html.H3("Chat", className="mb-3"),
        html.Div(
            style={"display": "flex", "flexDirection": "column", "height": "calc(100% - 40px)"},
            children=[
                # Chat display (scrollable)
                html.Div(
                    id="chat-display",
                    style={
                        "flex": "1 1 auto",
                        "overflowY": "auto",
                        "marginBottom": "10px",
                        "border": "1px solid #dee2e6",
                        "borderRadius": "5px",
                        "padding": "10px"
                    }
                ),

                # Options container (for buttons generated by the app)
                html.Div(
                    id="options-container",
                    style={"marginBottom": "10px"}
                ),
                # Fixed input area that doesn't scroll off-screen
                html.Div(
                    style={"flexShrink": "0"},
                    children=[
                        dbc.Input(
                            id="chat-input",
                            placeholder="Type your message here...",
                            type="text",
                            className="mb-2",
                            debounce=True,
                        ),
                        html.Div(
                            className="d-flex justify-content-between",
                            children=[
                                dbc.Button(
                                    "Send",
                                    id="send-button",
                                    color="primary",
                                    n_clicks=0
                                ),
                                dbc.Button(
                                    "Reset Application",
                                    id="reset-button",
                                    color="danger",
                                    n_clicks=0
                                )
                            ]
                        )
                    ]
                )
            ]
        )
    ], style={"height": "100%", "display": "flex", "flexDirection": "column"})
